[DP-113] 픽픽픽 이미지 업로드
dreamyPatisiel/devdevdev-server pull request #27
Opened 2024-03-21 14:55 UTC by ssosee

* 픽픽픽 이미지 업로드 구현
* S3를 사용하여 이미지를 업로드 합니다.

2024-03-22 05:36 UTC, yu-so-young2 requested changes
역시 천재만재개발자 세웅님! 이번에도 많이 배웠습니다 히히 수고하셨습니다!!!

2024-03-22 05:36 UTC, yu-so-young2 commented on src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java
> +        Member member = memberProvider.getMemberByAuthentication(authentication);
👍

2024-03-22 05:36 UTC, yu-so-young2 commented on src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java
> +        if(!name.equals(FIRST_PICK_OPTION_IMAGE) && !name.equals(SECOND_PICK_OPTION_IMAGE)) {
만일 name이 null로 들어오게 되면 NullPointerException이 발생할 수도 있겠다는 생각이 들어요!
name의 null 여부를 확인하는 로직을 넣으면 이 예외를 방지하고 커스텀 예외를 내려줄 수 있을 것 같습니다!

이와 별개로, NullPointerException을 방지하기 위해 `"string".equals(variable)` 형식으로 코드를 구현할 수 있다고 알고있는데(이 방식을 null-safe 비교 방식이라고 하네요!) 이 방식을 적용하는 것에 대해 어떻게 생각하시나요? (앞단에 null 확인 로직을 추가하면 굳이 필요하진 않지만, 자바 언어 개발에서는 null-safe를 지향하는 것이 좋다고 생각합니다!)

2024-03-22 05:36 UTC, yu-so-young2 commented on src/main/java/com/dreamypatisiel/devdevdev/global/common/MemberProvider.java
> +    public Member getMemberByAuthentication(Authentication authentication) {
여러 서비스 레이어에서 공통으로 사용되는 로직을 분리해주셨군요!!! 코드가 깔끔해져서 너무 좋네용 최고최고!!

2024-03-22 05:36 UTC, yu-so-young2 commented on src/main/java/com/dreamypatisiel/devdevdev/web/controller/request/PickOptionImageRequest.java
> +public class PickOptionImageRequest {
이 클래스는 어디서 사용될 예정인가요?

2024-03-22 05:36 UTC, yu-so-young2 commented on src/main/java/com/dreamypatisiel/devdevdev/web/response/BasicResponse.java
> +    private String errorMessageCode;
이부분 삭제가 안된 것 같아요!

2024-03-22 05:36 UTC, yu-so-young2 commented on src/main/java/com/dreamypatisiel/devdevdev/web/response/BasicResponse.java
> +    public static <T> BasicResponse<T> fail(String message, int errorCode, String errorMessageCode) {
이부분 삭제가 안된 것 같아요!

2024-03-22 11:23 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/DevdevdevApplication.java
> +@OpenAPIDefinition
앗 지난번에 스웨거에서 https 관련 default 경로(?) 관련해서 이슈가 생겼을 때 설정하고 삭제를 안했나봅니다!
삭제하도록 하겠습니다!

2024-03-22 11:24 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/LocalInitData.java
> +            PickOption pickOption = PickOption.create(new Title("픽옵션"+number), new PickOptionContents("픽콘텐츠"+number));
소영님 보다는 아니죠! ^0^

2024-03-22 11:28 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/aws/s3/AwsS3Uploader.java
> +            String imageUrl = amazonS3Client.getUrl(bucket, key).toString();
음.. 처음에는 같은 클래스에 있는 public 메소드 끼리 의존하면 안좋을 것 같다고 생각했는데...🤔
다시 생각해보니, uploads()와 upload() 메소드는 **업로드하는 행위는 동일**하고 단일, 다중 파일에 관한 부분이라서 다중 파일 업로드가 단일 파일 업로드를 의존하는 것이 더 좋아보이네요!
다중 파일 업로드에 문제가 생기면, 단일 파일 업로드에 문제가 있는 것이라고 판단할 수 있으니까요!!

날카로운 지적 감사해요~!! 
소영님 최고~👍

2024-03-22 11:31 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/aws/s3/AwsS3Uploader.java
> +                fileUploadMaxTryCount++;
음 원래 처음에 uploads() 에도 업로드가 실패하면, 예외가 발생하고 따로 서버측에서 업로드를 실행하도록 했는데요.
이부분은 나중에 AOP를 적용하면 고도화할 수 있을 것 같아서 제거했어요...!
upload() 메소드에도 마찬가지로 지금은 **재업로드 로직을 없애는 것** 어떻게 생각하시나요?!

SdkClientException, AmazonServiceException 예외는 한번 알아보도록 하겠습니당!
다시 한 번 날카로운 통찰력 감사해요~! 🙇🏻

2024-03-22 11:32 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/aws/s3/AwsS3Uploader.java
> +        return dirName + FileUtils.SLASH + filName;
부끄러운 오타입니당....😇

2024-03-22 11:34 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickRepositoryImpl.java
> +import java.util.Optional;
네 맞아요~!!
엘라스틱서치와 통일성을 위해서 변경하도록 할께용
이부분 이번 PR에 반영하도록 하겠습니다!!!!

최고다 쏘영쏘!

2024-03-22 11:34 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java
>      public static final String INVALID_FIND_PICKS_METHODS_CALL_MESSAGE = "익명 사용자가 아닙니다. 잘못된 메소드 호출 입니다.";
넵 알겠습니당!

2024-03-22 11:35 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java
> +        if(!name.equals(FIRST_PICK_OPTION_IMAGE) && !name.equals(SECOND_PICK_OPTION_IMAGE)) {
오!
맞아용
`"string".equals(variable)` 형식으로 코드로 변경하겠습니다!

2024-03-22 11:38 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/web/controller/request/PickOptionImageRequest.java
> +public class PickOptionImageRequest {
아 픽픽픽 작성 API에 사용하려고 했는데, 아직 기능이 없네용... 하하하하하....
이번 PR은 픽픽픽 옵션 이미지 업로드 API에 관련된 것이므로 삭제할께요~!!

2024-03-22 11:39 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/web/response/BasicResponse.java
> +    private String errorMessageCode;
네!
지난번에 develop 풀받았을때는 반영되었는데, rebase abort 하면서 다시 부활한 것 같네요..🥲

2024-03-22 11:39 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/web/response/BasicResponse.java
> +    public static <T> BasicResponse<T> fail(String message, int errorCode, String errorMessageCode) {
네!
이것두 지난번에 develop 풀받았을때는 반영되었는데, rebase abort 하면서 다시 부활한 것 같네요..🥲ㅌ

2024-03-23 07:57 UTC, yu-so-young2 commented on src/main/java/com/dreamypatisiel/devdevdev/aws/s3/AwsS3Uploader.java
> +            String imageUrl = amazonS3Client.getUrl(bucket, key).toString();
세웅님 이부분도 반영해주신 걸까요? 코드상으로는 그대로로 나와서요!

2024-03-23 08:08 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/aws/s3/AwsS3Uploader.java
> +            String imageUrl = amazonS3Client.getUrl(bucket, key).toString();
아 아직 이부분은 반영 안했어요!
감사합니다!!

이부분은 지금 upload 라는 행위(모든 파일을 업로드 할 수 있음을 내포)보다는 
이미지를 업로드만 가능한 메소드(uploadImage)로 변경하려고 합니다.

코드 수정하고 다시 한 번 이야기 나눠 보시죠! ^0^

2024-03-23 08:22 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/aws/s3/AwsS3Uploader.java
> +            String imageUrl = amazonS3Client.getUrl(bucket, key).toString();
아 그리고 이미지 업로드할 때, 서버에서 따로 재업로드 기능을 이번 PR에서는 넣지 않고 나중에 이미지 업로드 고도화 때 적용하려고 하는데, 소영님은 어떻게 생각하시나요?

지금 생각으로는 AOP를 사용하면 더 깔끔하게 구현할 수 있을 것 같아서요!

2024-03-23 10:02 UTC, yu-so-young2 commented on src/main/java/com/dreamypatisiel/devdevdev/aws/s3/AwsS3Uploader.java
> +            String imageUrl = amazonS3Client.getUrl(bucket, key).toString();
오 좋은 것 같아요 세웅님! 기능 구현 우선 머지하고, 추후에 고도화하면 좋을 것 같아요.
그리고 다중 이미지 업로드 시에 단일 업로드 public method를 의존하지 않고, 아래와 같이 이미지 업로드 기능을 수행하는 private 메서드를 다중/단일 이미지 업로드 메서드에서 공통으로 사용하는 것은 어떨까요?!

```
public 다중이미지업로드() {
        return multipartFiles.stream()
                .map(multipartFile -> 이미지업로드() )
                .toList();
}

public 단일이미지업로드() {
        return 이미지업로드()
}

private 이미지업로드() {
       // S3 이미지 업로드 로직...
}
```

2024-03-23 13:07 UTC, ssosee commented on src/main/java/com/dreamypatisiel/devdevdev/aws/s3/AwsS3Uploader.java
> +            String imageUrl = amazonS3Client.getUrl(bucket, key).toString();
오 확장성을 고려하신건가요?
레전드 레전드 레전드... 쏘영쏘...!!!!!!!!!!!!!!!!!!!!! 👍

private 메소드에 의존하도록 해서 확장성을 올려보께요

2024-03-23 15:17 UTC, yu-so-young2 commented
수고하셨습니다 세웅님!! 👍

2024-03-23 15:17 UTC, merged